name: HomesThatWork
main: com.dsnyder.homesthatwork.WorkingHomes
version: 2.3.0
author: Dan Snyder
description: A simple home plugin that actually works
commands:
  homesthatwork:
    description: Main plugin command. See /htw help for command list.
    usage: /homesthatwork [version | help [command]]
    aliases: [htw]
  home:
    description: See /htw help home
  sethome:
    description: See /htw help sethome
  delhome:
    description: See /htw help delhome
  listhomes:
    description: See /htw help listhomes
  homeinfo:
    description: See /htw help homeinfo
  goback:
    description: See /htw help goback
  htw-reload:
    description: See /htw help reload